LIFTWebApp/Controllers/LiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using LIFTWebApp.Models;
using LIFTWebApp.Models.ViewModels;

namespace LIFTWebApp.Controllers
{
    public class LiftController : Controller
    {
        private ILiftRepository repository;
        public int PageSize = 18;

        public LiftController(ILiftRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(int page = 1)
            => View(new LiftsListViewModel
            {
                Lifts = repository.Lifts
                    .OrderBy(p => p.LiftID)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Lifts.Count()
                }
            });

        public ViewResult Analytics()
            => View(new AnalyticsViewModel
            {
                Lifts = repository.Lifts
                    .OrderBy(p => p.LiftID),
                Exercises = repository.Exercises
                    .OrderBy(p => p.ExerciseName)
            });

        [HttpPost]
        public ViewResult Analytics(string ExerciseName)
        {
            ViewBag.Value = ExerciseName;

            return View(new AnalyticsViewModel
                {
                    Lifts = repository.Lifts
                        .OrderBy(p => p.LiftID),
                    Exercises = repository.Exercises
                        .OrderBy(p => p.ExerciseName),
                });
        }
    }
}

LIFTWebApp/Controllers/LiftsCURDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LIFTWebApp.Models;
using LIFTWebApp.Models.ViewModels;

namespace LIFTWebApp.Controllers
{
    public class LiftsCURDController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LiftsCURDController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LiftsCURD
        public async Task<IActionResult> Index()
        {
            return View(await _context.Lifts.ToListAsync());
        }

        // GET: LiftsCURD/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lift = await _context.Lifts
                .FirstOrDefaultAsync(m => m.LiftID == id);
            if (lift == null)
            {
                return NotFound();
            }

            return View(lift);
        }

        // GET: LiftsCURD/Create
        public IActionResult Create()
            => View(new NewLiftViewModel
               {
                   Lift = new Lift(),
                   Exercises = _context.Exercises
               });
        

        // POST: LiftsCURD/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LiftID,UserID,DateTimePerformed,ExercisePerfromed,Weight,Reps")] Lift lift)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lift);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lift);
        }

        // GET: LiftsCURD/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lift = await _context.Lifts.FindAsync(id);
            if (lift == null)
            {
                return NotFound();
            }
            return View(lift);
        }

        // POST: LiftsCURD/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LiftID,UserID,DateTimePerformed,ExercisePerfromed,Weight,Reps")] Lift lift)
        {
            if (id != lift.LiftID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lift);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LiftExists(lift.LiftID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lift);
        }

        // GET: LiftsCURD/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lift = await _context.Lifts
                .FirstOrDefaultAsync(m => m.LiftID == id);
            if (lift == null)
            {
                return NotFound();
            }

            return View(lift);
        }

        // POST: LiftsCURD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lift = await _context.Lifts.FindAsync(id);
            _context.Lifts.Remove(lift);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LiftExists(int id)
        {
            return _context.Lifts.Any(e => e.LiftID == id);
        }
    }
}

LIFTWebApp/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bungee|Open+Sans:600&display=swap" rel="stylesheet">

    <title>@ViewBag.Title</title>
    <style>
        .row-fluid {
            display: flex;
            justify-content: center;
        }

        html {
            height: 100%;
            box-sizing: border-box;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        body {
            position: relative;
            margin: 0;
            min-height: 100%;
            font-family: "Helvetica Neue", Arial, sans-serif;
            color: #90ADC6;
            background-color: #333652;
        }

        #mainDiv {
            padding-top: 20px;
            padding-bottom: 60px;
            font-size: 12pt;
        }

        .footer {
            position: absolute;
            right: 0;
            bottom: 0;
            left: 0;
            text-align: center;
        }

        .logo {
            font-family: 'Bungee', cursive;
            color: #FAD02C;
            font-size: 30px;
            text-decoration: none;
        }

        .logo:hover {
            color: #E9EAEC;
        }

        a:link {
            text-decoration: none;
        }

        .tabs {
            font-family: 'Bungee', cursive;
            color: #FAD02C;
            font-size: 15px;
            text-decoration: none;
        }

        .navbar-nav > li {
            padding-left: 10px;
            padding-right: 10px;
        }

        .link {
            display: inline-block;
            font-family: 'Bungee', cursive;
            text-decoration: none;
            color: #FAD02C;
            font-size: 15px;
            letter-spacing: 2px;
            text-transform: uppercase;
            position: relative;
            -webkit-transition: all 0.4s ease;
            transition: all 0.4s ease;
            padding: 15px;
            color: inherit;
        }

        .link:after {
            content: "";
            position: absolute;
            height: 5px;
            background-color: #FAD02C;
            width: 0;
            left: 50%;
            bottom: 0;
            -webkit-transform: translateX(-50%);
            -ms-transform: translateX(-50%);
            transform: translateX(-50%);
            -webkit-transition: 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55) all;
            transition: 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55) all;
        }

        .link:hover {
            color: #FAD02C;
        }

        .link:hover:after {
            width: 100%;
        }

         .navbar-toggle {
            background-color: #90ADC6 !important;
        }
        .navbar-inverse {
            border-color: #FAD02C !important;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark">

        <div class="container">


            <a class="navbar-brand logo" href="@Url.Action("Index" , "Home")">LIFT Fitness</a>
          
            <button class="navbar-toggler navbar-toggle navbar-inverse icon-bar" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link link" href="@Url.Action("Create" , "LiftsCURD")">Log Exercises</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link link" href="@Url.Action("List" , "Lift")">Lifts</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link link" href="@Url.Action("Analytics" , "Lift")">Analytics</a>
                    </li>

                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link link" href="@Url.Action("Profile" , "Account")">Account</a>
                        </li>

                        <li class="nav-item">
                            <form method="post" asp-action="logout" asp-controller="account">
                                <button type="submit" class="nav-link link btn btn-link"> Logout @User.Identity.Name</button>
                            </form>
                        </li>
                    }
                    else
                    {

                        <li class="nav-item">
                            <a class="nav-link link" href="@Url.Action("Register" , "Account")">Sign-Up</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link link" href="@Url.Action("Login" , "Account")">Login</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <div id="mainDiv">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="footer py-3 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; LIFT 2019</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>